#!/bin/bash
# ============================================================
# EXACT reproduction of the winning submission opt4_r728_116.csv
# Score: 0.58356 private / 0.55513 public — 3rd place
# Kaggle description: "4-comp: r728(11.6%) - squeeze the peak"
#
# The winning submission is a plain weighted average of 4
# component CSVs (no scale alignment), produced by
# scripts/plain_merge.py.
#
# Component files (generated by scripts/infer_4rc.py):
#   1. infer_train_v2_submission.csv  (52.2%)  MD5 9ece0f3a0a49a0727f23f2c3a2c967de
#   2. tta_flip_v2_submission.csv     (21.8%)  MD5 332177d9466adeafd6007536a7a72aca
#   3. 4rc_taba_merged.csv            (14.4%)  MD5 70a5f14420faab4d36a199ac66c549e6
#   4. res728_component.csv           (11.6%)  MD5 d3210701394e44500bb88271b9d6fd5b
#
# Expected output:
#   MD5    24d729dedd16de4f65e2d67301455c48
#   SHA256 9bb87a133f7af9d2f814373bc5a7f15b00be188d86619b440432fedd5470006e
#
# Usage:
#   bash scripts/reproduce_winning.sh /path/to/components_dir [output.csv]
#
# If the components dir contains only the .csv.gz files, they are
# decompressed automatically.
# ============================================================
set -e

COMPONENTS_DIR="${1:?Usage: reproduce_winning.sh <components_dir> [output.csv]}"
OUTPUT="${2:-submission_reproduced.csv}"

EXPECTED_MD5="24d729dedd16de4f65e2d67301455c48"
EXPECTED_SHA256="9bb87a133f7af9d2f814373bc5a7f15b00be188d86619b440432fedd5470006e"

COMPONENTS=(
    "infer_train_v2_submission.csv"
    "tta_flip_v2_submission.csv"
    "4rc_taba_merged.csv"
    "res728_component.csv"
)

# Auto-decompress components if only .gz versions are present
for c in "${COMPONENTS[@]}"; do
    if [ ! -f "$COMPONENTS_DIR/$c" ] && [ -f "$COMPONENTS_DIR/$c.gz" ]; then
        echo "Decompressing $c.gz ..."
        gunzip -kf "$COMPONENTS_DIR/$c.gz"
    fi
done

python3 -W ignore "$(dirname "$0")/plain_merge.py" \
  --csvs \
    "$COMPONENTS_DIR/infer_train_v2_submission.csv" \
    "$COMPONENTS_DIR/tta_flip_v2_submission.csv" \
    "$COMPONENTS_DIR/4rc_taba_merged.csv" \
    "$COMPONENTS_DIR/res728_component.csv" \
  --weights 0.522 0.218 0.144 0.116 \
  --output "$OUTPUT"

echo ""
echo "=== Cryptographic verification ==="

if command -v md5sum >/dev/null 2>&1; then
    ACTUAL_MD5=$(md5sum "$OUTPUT" | awk '{print $1}')
else
    ACTUAL_MD5=$(md5 -q "$OUTPUT")
fi
if command -v sha256sum >/dev/null 2>&1; then
    ACTUAL_SHA256=$(sha256sum "$OUTPUT" | awk '{print $1}')
else
    ACTUAL_SHA256=$(shasum -a 256 "$OUTPUT" | awk '{print $1}')
fi

echo "MD5    expected: $EXPECTED_MD5"
echo "MD5    actual:   $ACTUAL_MD5"
echo "SHA256 expected: $EXPECTED_SHA256"
echo "SHA256 actual:   $ACTUAL_SHA256"

if [ "$ACTUAL_MD5" = "$EXPECTED_MD5" ] && [ "$ACTUAL_SHA256" = "$EXPECTED_SHA256" ]; then
    echo ""
    echo "SUCCESS: bit-for-bit reproduction of the winning submission"
    echo "         opt4_r728_116.csv (0.58356 private / 0.55513 public)"
else
    echo ""
    echo "MISMATCH: output does not match the winning submission."
    exit 1
fi
